### ISSUE TITLE
What does "sapient" mean in the code of conduct?

### ISSUE THREAD

**Issue by das-g** [Xe/creators-code#3]
The [English version of your code of conduct](https://github.com/Xe/creators-code/blob/master/CODE_OF_CONDUCT.md) begins with

> We are sapient.  
> To be sapient is to be limited.

"sapient" has at least 3 distinct meanings in English:

1. wise, sage
2. being member of the species _homo sapiens_, i.e., being human
3. being member of a species (or other category), whose members are generally sufficiently sentient to be self-aware. (Like humans are, but not necessarily limited to only humans.)

All three would work in this context, giving significantly different meanings. (Though _wise_, _sage_ results in a meaning that might not be very plausible.) The [Toki Pona version](https://github.com/Xe/creators-code/blob/master/LIPU_PI_KULUPU_PONA.md) uses "jan" (_human being_, _person_, _somebody_), so that indeed rules out _wise_, _sage_ but still leaves both other meanings possible.

As "human" would be a much more common way to express the second meaning, I assume that the term "sapient" was chosen very consciously, either to aim for the third meaning or to deliberately create an ambiguity between the second and third meaning.

Which one is it?

(I'd like to know to better understand the code and because I consider to contribute a translation of the code and wonder how I should translate that part.)

**Comment by Xe** [comment]
The original draft of this had "human" instead of "sapient", but I changed it to be more generic and apply to any being that wants to contribute (regardless if they consider themselves "human" or not). Self-aware may be a better word there, but I'm really not sure what the best fit is.

I'd be honored to see other translations!

**Comment by ntoll** [comment]
Hello fellow travellers. :wave: I'm so pleased to have found this repository, and I had exactly the same question as raised by this issue. May I respectfully mention "[sentient](https://en.wikipedia.org/wiki/Sentience)" as a potential synonym/replacement for "human" or "sapient" - I specifically mean a capacity to subjectively experience and be present in the universe (no matter if one regards oneself as "human" or not).

I have a project for which this creator's code would be a welcome addition. Thank you for your efforts.

**Comment by Xe** [comment]
I like this idea @ntoll, I opened #5 with a `%s/sapient/sentient/g`

**Comment by ntoll** [comment]
For reference, now used [here](https://github.com/ntoll/textsmith). There's another project I'm just starting, for which this will be a great fit. I'll ping you when I have something to show for it.
